from fpdf import FPDF
from fpdf.enums import XPos, YPos
from datetime import datetime
from cve.cve_search import search_cves 
import os



def generate_pdf_report():

    # =====================================
    # Get Dynamic CVE Findings
    # =====================================

    results = search_cves("Apache") or []

    dynamic_findings = []

    for cve in results:
        dynamic_findings.append({
            "port": "80",
            "service": "Apache HTTP",
            "severity": cve["severity"].title(),
            "status": "Vulnerable"
        })

    scan_info = {
        "target_ip": "192.168.1.10",
        "scan_type": "Nmap Basic Scan",
        "generated_by": "SentinelAI CLI"
    }

    findings = dynamic_findings

    # =====================================
    # Windows Event Logs
    # =====================================

    event_logs = [
        {
            "event_id": 4625,
            "time": "02 August 2026, 11:15 AM",
            "user": "Administrator",
            "description": "Failed Login Attempt"
        },
        {
            "event_id": 4720,
            "time": "02 August 2026, 11:25 AM",
            "user": "John",
            "description": "New User Account Created"
        }
    ]

    # =====================================
    # MITRE ATT&CK Mapping
    # =====================================

    mitre_mappings = [
        {
            "technique_id": "T1021",
            "technique_name": "Remote Services"
        },
        {
            "technique_id": "T1110",
            "technique_name": "Brute Force"
        }
    ]

    # =====================================
    # OWASP Top 10 Mapping
    # =====================================

    owasp_mappings = [
        {
            "category": "A06",
            "name": "Vulnerable and Outdated Components"
        },
        {
            "category": "A07",
            "name": "Identification and Authentication Failures"
        }
    ]

    # =====================================
    # Remediation Steps
    # =====================================

    remediation_steps = [
        {
            "finding": "Apache HTTP Server",
            "severity": "High",
            "fix": [
                "Update Apache to the latest stable version.",
                "Apply all available security patches.",
                "Disable unnecessary Apache modules.",
                "Enable HTTPS using a valid TLS certificate."
            ]
        },
        {
            "finding": "Failed Login Attempts",
            "severity": "Medium",
            "fix": [
                "Review failed login attempts.",
                "Enable account lockout policy.",
                "Use strong passwords.",
                "Enable Multi-Factor Authentication (MFA)."
            ]
        }
    ]

    # =====================================
    # Create PDF
    # =====================================

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # =====================================
    # Title
    # =====================================

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(
        0,
        10,
        "SentinelAI CLI Security Report",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
        align="C"
    )

    pdf.ln(8)

    # =====================================
    # Scan Information
    # =====================================

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
    0,
    10,
    "Scan Information",
    new_x=XPos.LMARGIN,
    new_y=YPos.NEXT
)

    pdf.set_font("Helvetica", size=11)

    pdf.cell(
        0,
        7,
        f"Target IP: {scan_info['target_ip']}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.cell(
        0,
        7,
        f"Scan Type: {scan_info['scan_type']}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.cell(
        0,
        7,
        f"Generated By: {scan_info['generated_by']}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.cell(
        0,
        7,
        f"Date: {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.ln(6)

    # =====================================
    # Security Findings
    # =====================================

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
    0,
    10,
    "Security Findings",
    new_x=XPos.LMARGIN,
    new_y=YPos.NEXT
)

    # Table Header
    pdf.set_font("Helvetica", "B", 10)

    pdf.cell(25, 8, "Port", border=1)
    pdf.cell(55, 8, "Service", border=1)
    pdf.cell(45, 8, "Severity", border=1)
    pdf.cell(
        45,
        8,
        "Status",
        border=1,
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    # Table Data
    pdf.set_font("Helvetica", size=10)

    for finding in findings:

        pdf.cell(
            25,
            8,
            str(finding["port"]),
            border=1
        )

        pdf.cell(
            55,
            8,
            finding["service"],
            border=1
        )

        severity = finding["severity"]

        # Severity text color
        if severity.lower() == "critical":
            pdf.set_text_color(255, 0, 0)

        elif severity.lower() == "high":
            pdf.set_text_color(255, 140, 0)

        elif severity.lower() == "medium":
            pdf.set_text_color(255, 192, 0)

        elif severity.lower() == "low":
            pdf.set_text_color(0, 128, 0)

        else:
            pdf.set_text_color(128, 128, 128)

        pdf.cell(
            45,
            8,
            severity,
            border=1
        )

        # Reset text color
        pdf.set_text_color(0, 0, 0)

        pdf.cell(
            45,
            8,
            finding["status"],
            border=1,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )

    pdf.ln(6)

    # =====================================
    # Windows Event Logs
    # =====================================

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        10,
        "Windows Event Logs",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", "B", 9)

    pdf.cell(22, 8, "Event ID", border=1)
    pdf.cell(48, 8, "Time", border=1)
    pdf.cell(35, 8, "User", border=1)
    pdf.cell(
        65,
        8,
        "Description",
        border=1,
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", size=9)

    for log in event_logs:

        pdf.cell(
            22,
            8,
            str(log["event_id"]),
            border=1
        )

        pdf.cell(
            48,
            8,
            log["time"],
            border=1
        )

        pdf.cell(
            35,
            8,
            log["user"],
            border=1
        )

        pdf.cell(
            65,
            8,
            log["description"],
            border=1,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )

    pdf.ln(6)

    # =====================================
    # MITRE ATT&CK Mapping
    # =====================================

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        10,
        "MITRE ATT&CK Mapping",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", "B", 10)

    pdf.cell(45, 8, "Technique ID", border=1)
    pdf.cell(
        125,
        8,
        "Technique Name",
        border=1,
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", size=10)

    for technique in mitre_mappings:

        pdf.cell(
            45,
            8,
            technique["technique_id"],
            border=1
        )

        pdf.cell(
            125,
            8,
            technique["technique_name"],
            border=1,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )

    pdf.ln(6)

    # =====================================
    # OWASP Top 10 Mapping
    # =====================================

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        10,
        "OWASP Top 10 Mapping",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", "B", 10)

    pdf.cell(35, 8, "Category", border=1)
    pdf.cell(
        135,
        8,
        "OWASP Vulnerability",
        border=1,
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", size=10)

    for category in owasp_mappings:

        pdf.cell(
            35,
            8,
            category["category"],
            border=1
        )

        pdf.cell(
            135,
            8,
            category["name"],
            border=1,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )

    pdf.ln(6)

    # =====================================
    # Remediation Steps
    # =====================================

    pdf.set_font("Helvetica", "B", 14)

    pdf.set_x(pdf.l_margin)

    pdf.cell(
        0,
        10,
        "Remediation Steps",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    for item in remediation_steps:

        pdf.set_x(pdf.l_margin)

        pdf.set_font("Helvetica", "B", 11)

        pdf.multi_cell(
            0,
            7,
            f"{item['finding']} ({item['severity']} Severity)"
        )

        pdf.set_font("Helvetica", size=10)

        for step in item["fix"]:

            pdf.set_x(pdf.l_margin)

            pdf.multi_cell(
                0,
                6,
                f"- {step}"
            )

        pdf.ln(3)

    # =====================================
    # Summary
    # =====================================

    critical_count = sum(
        1 for finding in findings
        if finding["severity"].lower() == "critical"
    )

    high_count = sum(
        1 for finding in findings
        if finding["severity"].lower() == "high"
    )

    medium_count = sum(
        1 for finding in findings
        if finding["severity"].lower() == "medium"
    )

    low_count = sum(
        1 for finding in findings
        if finding["severity"].lower() == "low"
    )

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        10,
        "Summary",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", size=10)

    summary = (
        f"This report presents the results of the security assessment "
        f"performed on the target system ({scan_info['target_ip']}) "
        f"using the {scan_info['scan_type']}. During the scan, a total "
        f"of {len(findings)} security findings were identified. "
        f"The assessment detected {critical_count} Critical, "
        f"{high_count} High, {medium_count} Medium, and "
        f"{low_count} Low severity findings. Based on these results, "
        f"it is recommended to review the identified services and "
        f"implement the necessary security updates and remediation "
        f"measures to reduce potential security risks."
    )

    pdf.multi_cell(0, 6, summary)

    pdf.ln(5)

    # =====================================
    # Severity Statistics
    # =====================================

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(
    0,
    10,
    "Severity Statistics",
    new_x=XPos.LMARGIN,
    new_y=YPos.NEXT
)

    pdf.set_font("Helvetica", size=10)

    pdf.cell(
        0,
        6,
        f"- Total Findings: {len(findings)}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.cell(
        0,
        6,
        f"- Critical Severity: {critical_count}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.cell(
        0,
        6,
        f"- High Severity: {high_count}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.cell(
        0,
        6,
        f"- Medium Severity: {medium_count}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.cell(
        0,
        6,
        f"- Low Severity: {low_count}",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.ln(5)

    # =====================================
    # Conclusion
    # =====================================

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        10,
        "Conclusion",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", size=10)

    conclusion = (
        "The generated report provides a structured overview of the "
        "detected services and their associated security severity "
        "levels. Although the current implementation uses sample "
        "findings, the reporting engine is now fully dynamic and "
        "ready to integrate with real scan results from the SentinelAI "
        "scanning modules. This establishes a scalable foundation "
        "for automated vulnerability assessment and reporting."
    )

    pdf.multi_cell(0, 6, conclusion)

    pdf.ln(5)

    # =====================================
    # Future Enhancements
    # =====================================

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        10,
        "Future Enhancements",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", size=10)

    enhancements = [
        "Integration with live Nmap scan results",
        "Automatic CVE lookup using the NVD API",
        "CVSS-based risk scoring and prioritization",
        "MITRE ATT&CK framework mapping",
        "OWASP Top 10 vulnerability mapping",
        "AI-generated explanations and remediation suggestions",
        "Interactive dashboard for scan history and analytics",
        "PDF and HTML report generation",
        "Scheduled automated security scans",
        "Multi-host network scanning support"
    ]

    for feature in enhancements:
        pdf.cell(
            0,
            6,
            f"- {feature}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT
        )

    # =====================================
    # Save PDF
    # =====================================

    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    OUTPUT_DIR = os.path.join(
        BASE_DIR,
        "output"
    )

    os.makedirs(
        OUTPUT_DIR,
        exist_ok=True
    )

    output_file = os.path.join(
        OUTPUT_DIR,
        "SentinelAI_Report.pdf"
    )

    pdf.output(output_file)

    print("PDF report generated successfully!")
    print(f"Saved at: {output_file}")

    # Open PDF automatically on Windows
    os.startfile(output_file)


# =====================================
# Direct Execution
# =====================================

if __name__ == "__main__":
    generate_pdf_report()
# ============================================================
# Notes:
#
# This script generates a static PDF security report using
# the fpdf2 library.
#
# The report currently contains hardcoded sample findings to
# validate the PDF generation workflow.
#
# Future enhancements:
# • Dynamic Nmap scan results
# • NVD API (CVE) integration
# • MITRE ATT&CK mapping
# • OWASP Top 10 mapping
# • AI-generated analysis
# • Risk scoring and remediation guidance
#
# This file serves as the initial PDF report template for
# SentinelAI CLI.
# ============================================================