from sys import version

from docx import Document
from docx.shared import Pt
from docx.shared import RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from datetime import datetime
from cve.cve_search import search_cves 
from .executive_summary import generate_executive_summary
from .version_manager import next_version
import os

def generate_docx_report():
    
    results = search_cves("Apache")

    dynamic_findings = []

    for cve in results:
        dynamic_findings.append({
            "port": "80",
            "service": "Apache HTTP",
            "severity": cve["severity"].title(),
            "status": "Vulnerable"
        })

    scan_info = {
        "target_ip": "192.168.1.10",
        "scan_type": "Nmap Basic Scan",
        "generated_by": "SentinelAI CLI"
    }

    findings = dynamic_findings

    version = next_version(scan_info["target_ip"])
    filename = f"reports/docx/report_v{version}.docx"

    # Create a new Word document
    document = Document()

    # ===============================
    # Title
    # ===============================

    title = document.add_heading("SentinelAI CLI Security Report", level=1)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    document.add_paragraph()

    # ===============================
    # Executive Summary
    # ===============================

    summary = generate_executive_summary(scan_info, findings)

    document.add_heading("Executive Summary", level=1)
    document.add_paragraph(summary)

    # ===============================
    # Scan Information
    # ===============================

    document.add_heading("Scan Information", level=2)

    document.add_paragraph(f"Target IP: {scan_info['target_ip']}")
    document.add_paragraph(f"Scan Type: {scan_info['scan_type']}")
    document.add_paragraph(f"Generated By: {scan_info['generated_by']}")
    document.add_paragraph(
        f"Date: {datetime.now().strftime('%d %B %Y, %I:%M %p')}"
    )

    # ===============================
    # Findings
    # ===============================

    document.add_heading("Security Findings", level=2)

    table = document.add_table(rows=1, cols=4)

    table.style = "Table Grid"

    header = table.rows[0].cells

    header[0].text = "Port"
    header[1].text = "Service"
    header[2].text = "Severity"
    header[3].text = "Status"

    #loop through findings and add them to the table

    for finding in findings:
        row = table.add_row().cells

        row[0].text = finding["port"]
        row[1].text = finding["service"]
        row[2].text = finding["severity"]
        row[3].text = finding["status"]

        run = row[2].paragraphs[0].runs[0]

        severity = finding["severity"].lower()

        if severity == "critical":
            run.font.color.rgb = RGBColor(255, 0, 0)

        elif severity == "high":
            run.font.color.rgb = RGBColor(255, 140, 0)

        elif severity == "medium":
            run.font.color.rgb = RGBColor(255, 192, 0)

        elif severity == "low":
            run.font.color.rgb = RGBColor(0, 128, 0)

        else:
            run.font.color.rgb = RGBColor(128, 128, 128)

    # ===============================
    # Windows Event Logs
    # ===============================

    event_logs = [
        {
            "event_id": 4625,
            "time": "02 August 2026, 11:15 AM",
            "user": "Administrator",
            "description": "Failed Login Attempt"
        },
        {
            "event_id": 4720,
            "time": "02 August 2026, 11:25 AM",
            "user": "John",
            "description": "New User Account Created"
        }
    ]

    document.add_heading("Windows Event Logs", level=2)
    # Create Event Log Table

    event_table = document.add_table(rows=1, cols=4)
    event_table.style = "Table Grid"

    header = event_table.rows[0].cells

    header[0].text = "Event ID"
    header[1].text = "Time"
    header[2].text = "User"
    header[3].text = "Description"

    #Add event logs to the table

    for log in event_logs:
        row = event_table.add_row().cells

        row[0].text = str(log["event_id"])
        row[1].text = log["time"]
        row[2].text = log["user"]
        row[3].text = log["description"]

    document.add_paragraph()


    # ===============================
    # Sample MITRE ATT&CK Mapping
    # ===============================

    mitre_mappings = [
        {
            "technique_id": "T1021",
            "technique_name": "Remote Services"
        },
        {
            "technique_id": "T1110",
            "technique_name": "Brute Force"
        }
    ]

    # ===============================
    # Sample OWASP Mapping
    # ===============================

    owasp_mappings = [
        {
            "category": "A06",
            "name": "Vulnerable and Outdated Components"
        },
        {
            "category": "A07",
            "name": "Identification and Authentication Failures"
        }
    ]

    document.add_heading("MITRE ATT&CK Mapping", level=2)

    # Create MITRE Table
    mitre_table = document.add_table(rows=1, cols=2)
    mitre_table.style = "Table Grid"

    header = mitre_table.rows[0].cells

    header[0].text = "Technique ID"
    header[1].text = "Technique Name"

    for technique in mitre_mappings:

        row = mitre_table.add_row().cells

        row[0].text = technique["technique_id"]
        row[1].text = technique["technique_name"]

    document.add_paragraph()

    # ===============================
    # OWASP Top 10 Mapping
    # ===============================

    document.add_heading("OWASP Top 10 Mapping", level=2)

    owasp_table = document.add_table(rows=1, cols=2)
    owasp_table.style = "Table Grid"

    header = owasp_table.rows[0].cells

    header[0].text = "Category"
    header[1].text = "OWASP Vulnerability"

    for category in owasp_mappings:

        row = owasp_table.add_row().cells

        row[0].text = category["category"]
        row[1].text = category["name"]

    document.add_paragraph()

    # ===============================
    # Sample Remediation Steps
    # ===============================

    remediation_steps = [
        {
            "finding": "Apache HTTP Server",
            "severity": "High",
            "fix": [
                "Update Apache to the latest stable version.",
                "Apply all available security patches.",
                "Disable unnecessary Apache modules.",
                "Enable HTTPS using a valid TLS certificate."
            ]
        },
        {
            "finding": "Failed Login Attempts",
            "severity": "Medium",
            "fix": [
                "Review failed login attempts.",
                "Enable account lockout policy.",
                "Use strong passwords.",
                "Enable Multi-Factor Authentication (MFA)."
            ]
        }
    ]

    # ===============================
    # Remediation Steps
    # ===============================

    document.add_heading("Remediation Steps", level=2)

    for item in remediation_steps:

        document.add_heading(
            f"{item['finding']} ({item['severity']} Severity)",
            level=3
        )

        for step in item["fix"]:
            document.add_paragraph(
                step,
                style="List Bullet"
            )

        document.add_paragraph()


    # ===============================
    # Summary
    # ===============================

    critical_count = sum(1 for finding in findings if finding["severity"].lower() == "critical")
    high_count = sum(1 for finding in findings if finding["severity"].lower() == "high")
    medium_count = sum(1 for finding in findings if finding["severity"].lower() == "medium")
    low_count = sum(1 for finding in findings if finding["severity"].lower() == "low")

    document.add_heading("Summary", level=2)

    document.add_paragraph(
        f"This report presents the results of the security assessment performed "
        f"on the target system ({scan_info['target_ip']}) using the "
        f"{scan_info['scan_type']}. During the scan, a total of {len(findings)} "
        f"security findings were identified. The assessment detected "
        f"{critical_count} Critical, {high_count} High, "
        f"{medium_count} Medium, and {low_count} Low severity findings. "
        f"Based on these results, it is recommended to review the identified "
        f"services and implement the necessary security updates and remediation "
        f"measures to reduce potential security risks."
    )

    document.add_paragraph()

    document.add_heading("Severity Statistics", level=3)

    stats = document.add_paragraph()

    stats.add_run(f"• Total Findings: {len(findings)}\n")
    stats.add_run(f"• Critical Severity: {critical_count}\n")
    stats.add_run(f"• High Severity: {high_count}\n")
    stats.add_run(f"• Medium Severity: {medium_count}\n")
    stats.add_run(f"• Low Severity: {low_count}")
    document.add_heading("Conclusion", level=2)

    document.add_paragraph(
        "The generated report provides a structured overview of the detected "
        "services and their associated security severity levels. Although the "
        "current implementation uses sample findings, the reporting engine is "
        "now fully dynamic and ready to integrate with real scan results from "
        "the SentinelAI scanning modules. This establishes a scalable foundation "
        "for automated vulnerability assessment and reporting."
    )

    # ===============================
    # Future Scope
    # ===============================

    document.add_heading("Future Enhancements", level=2)

    document.add_paragraph(
        "• Integration with live Nmap scan results\n"
        "• Automatic CVE lookup using the NVD API\n"
        "• CVSS-based risk scoring and prioritization\n"
        "• MITRE ATT&CK framework mapping\n"
        "• OWASP Top 10 vulnerability mapping\n"
        "• AI-generated explanations and remediation suggestions\n"
        "• Interactive dashboard for scan history and analytics\n"
        "• PDF and HTML report generation\n"
        "• Scheduled automated security scans\n"
        "• Multi-host network scanning support"
    )

    # ===============================
    # Save Versioned Report
    # ===============================

    # Current version number (already generated earlier)
    # version = next_version(scan_info["target_ip"])

    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    # Go from report/ → research/ → sentinal/ → team-finatics/
    PROJECT_ROOT = os.path.abspath(os.path.join(BASE_DIR, "..", "..", ".."))

    DOCX_DIR = os.path.join(PROJECT_ROOT, "reports", "docx")
    os.makedirs(DOCX_DIR, exist_ok=True)

    output_file = os.path.join(DOCX_DIR, f"report_v{version}.docx")

    document.save(output_file)

    print("Report generated successfully!")
    print(f"Saved at: {output_file}")

# Open automatically on Windows
    os.startfile(output_file)


if __name__ == "__main__":
    generate_docx_report()

# ============================================================
# Notes:
#
# This script generates a static Microsoft Word (.docx) report
# using the python-docx library.
#
# The report currently contains hardcoded test data to verify
# the report generation workflow.
#
# In future development, this static data will be replaced with:
#
# • Real Nmap scan results
# • CVE information from the NVD API
# • MITRE ATT&CK mappings
# • OWASP Top 10 mappings
# • AI-generated explanations
# • Risk scoring and remediation recommendations
#
# This serves as the initial report template for SentinelAI CLI.
# ============================================================


# ============================================================
# MITRE ATT&CK Mapping

# Displays MITRE ATT&CK techniques mapped
# to identified security findings.
# Currently uses sample data.
# Future integration will consume the
# mapping engine output automatically.

# ============================================================
# ===============================
# OWASP Top 10 Mapping
# ===============================
# Displays OWASP Top 10 categories
# associated with detected vulnerabilities.
# Currently uses sample mappings.
# Future versions will integrate with
# the OWASP mapping module.