from fpdf import FPDF
import os

# =====================================
# Create PDF Object
# =====================================

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()

# =====================================
# Title
# =====================================

pdf.set_font("Helvetica", "B", 18)
pdf.cell(0, 10, "SentinelAI CLI Security Report", ln=True, align="C")

pdf.ln(10)

# =====================================
# Scan Information
# =====================================

pdf.set_font("Helvetica", "B", 14)
pdf.cell(0, 10, "Scan Information", ln=True)

pdf.set_font("Helvetica", size=12)

pdf.cell(0, 8, "Target IP: 192.168.1.10", ln=True)
pdf.cell(0, 8, "Scan Type: Nmap Basic Scan", ln=True)
pdf.cell(0, 8, "Generated By: SentinelAI CLI", ln=True)
pdf.cell(0, 8, "Date: July 19, 2026", ln=True)

pdf.ln(8)

# =====================================
# Security Findings
# =====================================

pdf.set_font("Helvetica", "B", 14)
pdf.cell(0, 10, "Security Findings", ln=True)

pdf.set_font("Helvetica", "B", 12)

pdf.cell(30, 10, "Port", border=1)
pdf.cell(60, 10, "Service", border=1)
pdf.cell(40, 10, "Severity", border=1)
pdf.cell(40, 10, "Status", border=1, ln=True)

pdf.set_font("Helvetica", size=12)

findings = [
    ["22", "SSH", "Low", "Open"],
    ["80", "HTTP", "Medium", "Open"],
    ["443", "HTTPS", "Low", "Open"],
    ["3389", "RDP", "High", "Open"]
]

for item in findings:
    pdf.cell(30, 10, item[0], border=1)
    pdf.cell(60, 10, item[1], border=1)
    pdf.cell(40, 10, item[2], border=1)
    pdf.cell(40, 10, item[3], border=1, ln=True)

pdf.ln(8)

# =====================================
# Summary
# =====================================

pdf.set_font("Helvetica", "B", 14)
pdf.cell(0, 10, "Summary", ln=True)

pdf.set_font("Helvetica", size=12)

summary = (
    "This is a static sample report generated for development purposes. "
    "The findings shown above are hardcoded test data and will later "
    "be replaced with actual scan results."
)

pdf.multi_cell(0, 8, summary)

pdf.ln(5)

# =====================================
# Future Enhancements
# =====================================

pdf.set_font("Helvetica", "B", 14)
pdf.cell(0, 10, "Future Enhancements", ln=True)

pdf.set_font("Helvetica", size=12)

enhancements = [
    "Dynamic scan results",
    "CVE Lookup Integration",
    "MITRE ATT&CK Mapping",
    "OWASP Top 10 Mapping",
    "AI-generated Explanation",
    "PDF Report Generation"
]

for feature in enhancements:
    pdf.cell(5)
    pdf.cell(0, 8, f"- {feature}", ln=True)

# =====================================
# Save PDF
# =====================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

output_file = os.path.join(OUTPUT_DIR, "SentinelAI_Report.pdf")

pdf.output(output_file)

print("PDF report generated successfully!")
print(f"Saved at: {output_file}")

# Open the generated PDF automatically (Windows)
os.startfile(output_file)

# ============================================================
# Notes:
#
# This script generates a static PDF security report using
# the fpdf2 library.
#
# The report currently contains hardcoded sample findings to
# validate the PDF generation workflow.
#
# Future enhancements:
# • Dynamic Nmap scan results
# • NVD API (CVE) integration
# • MITRE ATT&CK mapping
# • OWASP Top 10 mapping
# • AI-generated analysis
# • Risk scoring and remediation guidance
#
# This file serves as the initial PDF report template for
# SentinelAI CLI.
# ============================================================