from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
import os


# Create a new Word document
document = Document()

# ===============================
# Title
# ===============================

title = document.add_heading("SentinelAI CLI Security Report", level=1)
title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

document.add_paragraph()

# ===============================
# Scan Information
# ===============================

document.add_heading("Scan Information", level=2)

document.add_paragraph("Target IP: 192.168.1.10")
document.add_paragraph("Scan Type: Nmap Basic Scan")
document.add_paragraph("Generated By: SentinelAI CLI")
document.add_paragraph("Date: July 19, 2026")

# ===============================
# Findings
# ===============================

document.add_heading("Security Findings", level=2)

table = document.add_table(rows=1, cols=4)

table.style = "Table Grid"

header = table.rows[0].cells

header[0].text = "Port"
header[1].text = "Service"
header[2].text = "Severity"
header[3].text = "Status"

# Static Test Data

findings = [
    ["22", "SSH", "Low", "Open"],
    ["80", "HTTP", "Medium", "Open"],
    ["443", "HTTPS", "Low", "Open"],
    ["3389", "RDP", "High", "Open"]
]

for finding in findings:
    row = table.add_row().cells

    row[0].text = finding[0]
    row[1].text = finding[1]
    row[2].text = finding[2]
    row[3].text = finding[3]

# ===============================
# Summary
# ===============================

document.add_heading("Summary", level=2)

document.add_paragraph(
    "This is a static sample report generated for development purposes. "
    "The findings shown above are hardcoded test data and will later be "
    "replaced with actual scan results."
)

# ===============================
# Future Scope
# ===============================

document.add_heading("Future Enhancements", level=2)

document.add_paragraph(
    "- Dynamic scan results\n"
    "- CVE Lookup Integration\n"
    "- MITRE ATT&CK Mapping\n"
    "- OWASP Mapping\n"
    "- AI-generated Explanation\n"
    "- PDF Report Generation"
)

# ===============================
# Save Report
# ===============================


# Get the directory where this script is located
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Create the output folder inside the report directory
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Full path of the report
output_file = os.path.join(OUTPUT_DIR, "SentinelAI_Report.docx")

# Save the document
document.save(output_file)

print("Report generated successfully!")
print(f"Saved at: {output_file}")

# Open the report automatically (Windows)
os.startfile(output_file)


# ============================================================
# Notes:
#
# This script generates a static Microsoft Word (.docx) report
# using the python-docx library.
#
# The report currently contains hardcoded test data to verify
# the report generation workflow.
#
# In future development, this static data will be replaced with:
#
# • Real Nmap scan results
# • CVE information from the NVD API
# • MITRE ATT&CK mappings
# • OWASP Top 10 mappings
# • AI-generated explanations
# • Risk scoring and remediation recommendations
#
# This serves as the initial report template for SentinelAI CLI.
# ============================================================