import os
from datetime import datetime
from cve.cve_search import search_cves
from .executive_summary import generate_executive_summary



def generate_markdown_report():
    results = search_cves("Apache")
    dynamic_findings = []

    for cve in results:
        dynamic_findings.append({
            "port": "80",
            "service": "Apache HTTP",
            "severity": cve["severity"].title(),
            "status": "Vulnerable"
        })

    # Outside the loop
    scan_info = {
        "target_ip": "192.168.1.10",
        "scan_type": "Nmap Basic Scan",
        "generated_by": "SentinelAI CLI"
    }

    findings = dynamic_findings

    event_logs = [
        {
            "event_id": 4625,
            "time": "02 August 2026, 11:15 AM",
            "user": "Administrator",
            "description": "Failed Login Attempt"
        },
        {
            "event_id": 4720,
            "time": "02 August 2026, 11:25 AM",
            "user": "John",
            "description": "New User Account Created"
        }
    ]

    
    summary = generate_executive_summary(scan_info, findings)

    markdown = "# Executive Summary\n\n"
    markdown += summary + "\n\n"

    # ===============================
    # Sample MITRE ATT&CK Mapping
    # ===============================

    mitre_mappings = [
        {
            "technique_id": "T1021",
            "technique_name": "Remote Services"
        },
        {
            "technique_id": "T1110",
            "technique_name": "Brute Force"
        }
    ]

    # ===============================
    # Sample OWASP Mapping
    # ===============================

    owasp_mappings = [
        {
            "category": "A06",
            "name": "Vulnerable and Outdated Components"
        },
        {
            "category": "A07",
            "name": "Identification and Authentication Failures"
        }
    ]

    remediation_steps = [
        {
            "finding": "Apache HTTP Server",
            "severity": "High",
            "fix": [
                "Update Apache to the latest stable version.",
                "Apply all available security patches.",
                "Disable unnecessary Apache modules.",
                "Enable HTTPS using a valid TLS certificate."
            ]
        },
        {
            "finding": "Failed Login Attempts",
            "severity": "Medium",
            "fix": [
                "Review failed login attempts.",
                "Enable account lockout policy.",
                "Use strong passwords.",
                "Enable Multi-Factor Authentication (MFA)."
            ]
        }
    ]

    markdown += "# sentinalAI Security Report\n\n"
    markdown += "## Scan Information\n\n"
    markdown += f"- **Target IP:** {scan_info['target_ip']}\n"
    markdown += f"- **Scan Type:** {scan_info['scan_type']}\n"
    markdown += f"- **Generated By:** {scan_info['generated_by']}\n"
    markdown += f"- **Date:** {datetime.now().strftime('%d %B %Y, %I:%M %p')}\n\n"

    # ===============================
    # Security Findings
    # ===============================

    markdown += "## Security Findings\n\n"
    markdown += "| Port | Service | Severity | Status |\n"
    markdown += "|------|---------|----------|--------|\n"

    for finding in findings:
        markdown += (
            f"| {finding['port']} | "
            f"{finding['service']} | "
            f"{finding['severity']} | "
            f"{finding['status']} |\n"
        )

    markdown += "\n"

    # ===============================
    # Windows Event Logs
    # ===============================

    markdown += "## Windows Event Logs\n\n"
    markdown += "| Event ID | Time | User | Description |\n"
    markdown += "|----------|------|------|-------------|\n"

    for log in event_logs:
        markdown += (
            f"| {log['event_id']} | "
            f"{log['time']} | "
            f"{log['user']} | "
            f"{log['description']} |\n"
        )

    markdown += "\n"

    # ===============================
    # MITRE ATT&CK Mapping
    # ===============================

    markdown += "## MITRE ATT&CK Mapping\n\n"
    markdown += "| Technique ID | Technique Name |\n"
    markdown += "|--------------|----------------|\n"

    for item in mitre_mappings:
        markdown += (
            f"| {item['technique_id']} | "
            f"{item['technique_name']} |\n"
        )

    markdown += "\n"

    # ===============================
    # OWASP Top 10 Mapping
    # ===============================

    markdown += "## OWASP Top 10 Mapping\n\n"
    markdown += "| Category | Vulnerability |\n"
    markdown += "|----------|---------------|\n"

    for item in owasp_mappings:
        markdown += (
            f"| {item['category']} | "
            f"{item['name']} |\n"
        )

    markdown += "\n"

    # ===============================
    # Remediation Steps
    # ===============================

    markdown += "## Remediation Steps\n\n"

    for item in remediation_steps:
        markdown += (
            f"### {item['finding']} "
            f"({item['severity']} Severity)\n\n"
        )

        for step in item["fix"]:
            markdown += f"- {step}\n"

        markdown += "\n"

    # ===============================
    # Summary
    # ===============================

    markdown += "## Summary\n\n"
    markdown += (
        f"This security assessment identified **{len(findings)}** findings "
        f"on the target system **{scan_info['target_ip']}**. "
        "The report includes vulnerability details, Windows Event Logs, "
        "MITRE ATT&CK mappings, OWASP Top 10 mappings, "
        "and recommended remediation steps.\n"
    )

    # ===============================
    # Save Markdown Report
    # ===============================

    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "output")
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, "SentinelAI_Report.md")

    with open(output_file, "w", encoding="utf-8") as file:
        file.write(markdown)

    print("Markdown report generated successfully!")
    print(f"Saved at: {output_file}")

    os.startfile(output_file)


if __name__ == "__main__":
    generate_markdown_report()
