from docx import Document
from docx.shared import Pt
from docx.shared import RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from datetime import datetime
from cve.cve_search import search_cves 
import os

results = search_cves("Apache")

dynamic_findings = []

for cve in results:
    dynamic_findings.append({
        "port": "80",
        "service": "Apache HTTP",
        "severity": cve["severity"].title(),
        "status": "Vulnerable"
    })

scan_info = {
    "target_ip": "192.168.1.10",
    "scan_type": "Nmap Basic Scan",
    "generated_by": "SentinelAI CLI"
}

findings = dynamic_findings

# Create a new Word document
document = Document()

# ===============================
# Title
# ===============================

title = document.add_heading("SentinelAI CLI Security Report", level=1)
title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

document.add_paragraph()

# ===============================
# Scan Information
# ===============================

document.add_heading("Scan Information", level=2)


document.add_paragraph(f"Target IP: {scan_info['target_ip']}")
document.add_paragraph(f"Scan Type: {scan_info['scan_type']}")
document.add_paragraph(f"Generated By: {scan_info['generated_by']}")
document.add_paragraph(
    f"Date: {datetime.now().strftime('%d %B %Y, %I:%M %p')}"
)

# ===============================
# Findings
# ===============================

document.add_heading("Security Findings", level=2)

table = document.add_table(rows=1, cols=4)

table.style = "Table Grid"

header = table.rows[0].cells

header[0].text = "Port"
header[1].text = "Service"
header[2].text = "Severity"
header[3].text = "Status"

#loop through findings and add them to the table

for finding in findings:
    row = table.add_row().cells

    row[0].text = finding["port"]
    row[1].text = finding["service"]
    row[2].text = finding["severity"]
    row[3].text = finding["status"]

    run = row[2].paragraphs[0].runs[0]

    severity = finding["severity"].lower()

    if severity == "critical":
        run.font.color.rgb = RGBColor(255, 0, 0)

    elif severity == "high":
        run.font.color.rgb = RGBColor(255, 140, 0)

    elif severity == "medium":
        run.font.color.rgb = RGBColor(255, 192, 0)

    elif severity == "low":
        run.font.color.rgb = RGBColor(0, 128, 0)

    else:
        run.font.color.rgb = RGBColor(128, 128, 128)

# ===============================
# Summary
# ===============================

critical_count = sum(1 for finding in findings if finding["severity"].lower() == "critical")
high_count = sum(1 for finding in findings if finding["severity"].lower() == "high")
medium_count = sum(1 for finding in findings if finding["severity"].lower() == "medium")
low_count = sum(1 for finding in findings if finding["severity"].lower() == "low")

document.add_heading("Summary", level=2)

document.add_paragraph(
    f"This report presents the results of the security assessment performed "
    f"on the target system ({scan_info['target_ip']}) using the "
    f"{scan_info['scan_type']}. During the scan, a total of {len(findings)} "
    f"security findings were identified. The assessment detected "
    f"{critical_count} Critical, {high_count} High, "
    f"{medium_count} Medium, and {low_count} Low severity findings. "
    f"Based on these results, it is recommended to review the identified "
    f"services and implement the necessary security updates and remediation "
    f"measures to reduce potential security risks."
)

document.add_paragraph()

document.add_heading("Severity Statistics", level=3)

stats = document.add_paragraph()

stats.add_run(f"• Total Findings: {len(findings)}\n")
stats.add_run(f"• Critical Severity: {critical_count}\n")
stats.add_run(f"• High Severity: {high_count}\n")
stats.add_run(f"• Medium Severity: {medium_count}\n")
stats.add_run(f"• Low Severity: {low_count}")
document.add_heading("Conclusion", level=2)

document.add_paragraph(
    "The generated report provides a structured overview of the detected "
    "services and their associated security severity levels. Although the "
    "current implementation uses sample findings, the reporting engine is "
    "now fully dynamic and ready to integrate with real scan results from "
    "the SentinelAI scanning modules. This establishes a scalable foundation "
    "for automated vulnerability assessment and reporting."
)

# ===============================
# Future Scope
# ===============================

document.add_heading("Future Enhancements", level=2)

document.add_paragraph(
    "• Integration with live Nmap scan results\n"
    "• Automatic CVE lookup using the NVD API\n"
    "• CVSS-based risk scoring and prioritization\n"
    "• MITRE ATT&CK framework mapping\n"
    "• OWASP Top 10 vulnerability mapping\n"
    "• AI-generated explanations and remediation suggestions\n"
    "• Interactive dashboard for scan history and analytics\n"
    "• PDF and HTML report generation\n"
    "• Scheduled automated security scans\n"
    "• Multi-host network scanning support"
)

# ===============================
# Save Report
# ===============================


# Get the directory where this script is located
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Create the output folder inside the report directory
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Full path of the report
output_file = os.path.join(OUTPUT_DIR, "SentinelAI_Report.docx")

# Save the document
document.save(output_file)

print("Report generated successfully!")
print(f"Saved at: {output_file}")

# Open the report automatically (Windows)
os.startfile(output_file)


# ============================================================
# Notes:
#
# This script generates a static Microsoft Word (.docx) report
# using the python-docx library.
#
# The report currently contains hardcoded test data to verify
# the report generation workflow.
#
# In future development, this static data will be replaced with:
#
# • Real Nmap scan results
# • CVE information from the NVD API
# • MITRE ATT&CK mappings
# • OWASP Top 10 mappings
# • AI-generated explanations
# • Risk scoring and remediation recommendations
#
# This serves as the initial report template for SentinelAI CLI.
# ============================================================